name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v3

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalacja zależności
        run: pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v3

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalacja zależności
        run: pip install -r requirements.txt

      - name: Uruchomienie testów
        run: pytest
